### ISSUE TITLE
demo jsbin not working in safari and ipad

### ISSUE THREAD

**Issue by abulka** [Stuhl/javascript-entity-component-system#2]
The demo jsbin not working in safari and ipad, but works ok in Chrome.  FYI.
https://jsbin.com/bunetigumo/edit?html,output

**Comment by Stuhl** [comment]
Hey there, thanks for reporting this. I haven't really thought about giving the demo support for Ipad but I'll have a look what I can do. Strange though that JSBin doesn't work on Safari, I haven't tested it but I would be pretty sure that it would work.

Neitherless to say I'll look if I can host the demo on a different site to also support some older browsers.

**Comment by Stuhl** [comment]
Hey @abulka, been a while.

I don't think that the issue is a problem anymore since safari has got alot of updates which should resolve the problem. It's not a big deal either if it's still broken because in the future (when the time comes) I will host the demo on github pages with tutorials and such. 

Until then the basic demo and mini tutorial should do the job.

Cheers
