### ISSUE TITLE
Polyphony, synergies and future

### ISSUE THREAD

**Issue by dumblob** [Stuhl/javascript-entity-component-system#3]
I wonder whether you saw [Polyphony](https://pepite-depot.univ-lille.fr/LIBRE/EDSPI/2019/50376-2019-Raffaillac.pdf ) (another ECS system in JavaScript) and its caveats. It might be interesting to get some inspiration there.

Also, what is actually planned for the future of javascript-entity-component-system?

Feel free to take a look at the discussion about Polyphony "future" on https://github.com/traffaillac/traffaillac.github.io/issues/1 .

**Comment by Stuhl** [comment]
Hey @dumblob, sorry for not answering earlier. I didn't get a notification from github.

I can't read the paper unfortunately, it's all french.

Frankly I made the "library" 2 years ago and there hasn't been much progress on it than simple ideas from day to day in my head. I probably won't continue making commits to it since there are many alternatives that are more sophisticated in both features and performance. Also I'm quite busy with other stuff which means I simply don't have the time to improve it.

I have some ideas for simple 2D games where this lib would very suited for it. If I have free time once some of my other projects finish, I might continue working on this library.

You're happy to get into the code (it's not that long anyways, 200 lines at most) and make a PR with some improvements. I'm happy to talk about features and ideas :)

Cheers

**Comment by dumblob** [comment]
I see, thanks anyway for your insight and the work on this!
